### ISSUE TITLE
lookspcode enhancement

### ISSUE THREAD

**Issue by gistin** [izaopenshaw/TreeCarbon#3]
This could be streamlined
1. do we need to specify conifer or broadleaf, just look up either
2. do we need to specify common or botanical, could just search both

for common names caps are all over the place (from the orginal data)? shall we make them all lowercase and the user lookup tolower(s)?

**Comment by izaopenshaw** [comment]
1. For broadleaf or conifer, while it is potentially annoying to have to input this data, its what the function falls back on if the name of the species hasn't been found in data(lookup_df) (which I hope has been coming through for you now?) as there is a general species code for broadleaf and one for conifer.
2. I had thought about doing this for common or botanical so thank you for flagging this, that's now been amended. 
3. the function already searches tolower version of input name :)

**Comment by gistin** [comment]
1. As yes that make sense as at this point it just uses a generic conifer or broadleaf. At some time in the far future this should be integrated with Kew plant names etc, but lots of trees will not be either category! Also possibly have a fussy look up (but again for the far future)
2. Great
3. Sorry I didn't check deeply, great
